apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - database-config.yaml
  - user-config.yaml
  - cache-config.yaml
  - password-secret.yaml
  - templates.yaml
  - ingress.yaml

transformers:
  - transformer.yaml
