apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

configMapGenerator:
  - name: cache-config
    literals:
      - cacheHost=redis
      - cachePort=6379
      - cacheDb=3
  - name: database-config
    literals:
      - name=mydb
      - host=mongodb
      - port=27017
  - name: user-config
    literals:
      - username=testuser
  - name: templates
    files:
      - index.tmpl

secretGenerator:
  - name: demo-secret
    literals:
      - PASSWORD=s3cr3t1234
      - MONGO_URL=mongodb://{{.username}}:{{.password}}@{{.db.host}}:{{.db.port}}/{{.db.name}}

resources:
  - ingress.yaml

transformers:
  - transformer.yaml
