apiVersion: noris.net/v1alpha1
kind: GeneralReplacementsTransformer
metadata:
  name: example

values:
  hostname: foo.{{.domain}} # can be overwritten by selectValues
  domain: example.com

valuesFile: values.yaml

selectValues:
  - name: namespace # key name
    resource: # resource to extract value from
      kind: ConfigMap
      name: database-config
      fieldPath: metadata.namespace
  - name: username
    resource:
      kind: ConfigMap
      name: user-config
      fieldPath: data.username
  - name: db
    resource:
      kind: ConfigMap
      name: database-config
      fieldPath: data.* # load all kv's, e.g. as db.name, db.host...
  - name: dummy
    resource:
      kind: ConfigMap
      name: cache-config
      fieldPath: data.* # load all kv's...
    splat: true # ...to the root level, e.g. cacheHost, cachePort...
  - name: password
    resource:
      kind: Secret
      name: demo-secret
      fieldPath: data.PASSWORD
  - name: oops
    resource:
      kind: ConfigMap
      name: missing
      fieldPath: data.abc

replacements:
  - resource:
      kind: ConfigMap
      name: templates
    type: template
    delimiters: # use non-default delimiters
      - "[["
      - "]]"
  - resource:
      kind: Ingress
      # no name -> process all Ingresses
    type: template
  - resource:
      kind: Secret
      name: demo-secret
    type: template
